### PR TITLE
Market -- approval ack

### LINKED ISSUE #921: wait for agreement approval (req) should return AFTER approve (prov)
Now it is not guaranteed, which causes
```
[2021-01-13 16:26:59,512 ERROR yapapi.rest] Failed to create activity for agreement c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
```

because
```
[2021-01-13T15:26:59Z DEBUG actix_web::middleware::logger] Error in response: BadRequest("Agreement c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3 is not Approved. Current state: Pending")
```

Provider's approval event is emitted after Requestor's approval event

## Requestor
```
sqlite> select * from market_agreement_event where agreement_id like '%c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3';
          id = 3
agreement_id = R-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Approved
   timestamp = 2021-01-13 15:26:59.379966
      issuer = P
      reason = 
   signature = 

          id = 5
agreement_id = R-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Terminated
   timestamp = 2021-01-13 15:27:18.260629
      issuer = R
      reason = {"message":"Successfully finished all work","golem.requestor.code":"Success"}
   signature = 
```

## Provider
```
sqlite> select * from market_agreement_event where agreement_id like '%c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3';
          id = 134
agreement_id = P-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Approved
   timestamp = 2021-01-13 15:26:59.472703322
      issuer = P
      reason = 
   signature = 

          id = 135
agreement_id = P-c1652ec82bd1c57464fe68f14e4ad113cee4f27aa1ce9df37c69994a8d86abf3
  event_type = Terminated
   timestamp = 2021-01-13 15:27:18.200151809
      issuer = R
      reason = {"message":"Successfully finished all work","golem.requestor.code":"Success"}
   signature = 
```

This is minor, because `yapapi` is able to handle it correctly via retry

### PR DESCRIPTION
**Pull request by nieznanysprawiciel**
Remember to change base to `release/v0.6` before merging

Resolves #921

### CODE REVIEW

File: core/market/src/negotiation/provider.rs [hunk 1]
```diff
@@ -228,37 +230,110 @@ impl ProviderBroker {
...
+            // TODO: Update state to `AgreementState::Approving`.
 
             agreement
         };
 
-        self.common.notify_agreement(&agreement).await;
+        // It doesn't have to be under lock, since we have `Approving` state.
+        // Note that this state change between `Approving` and `Pending` in both
+        // ways is invisible for REST and GSB user, because `Approving` is only our
+        // internal state and is mapped to `Pending`.
```
Comment (jiivan) [inline core/market/src/negotiation/provider.rs:252]: :+1:

File: core/market/src/negotiation/provider.rs [hunk 2]
```diff
@@ -228,37 +230,110 @@ impl ProviderBroker {
...
+async fn agreement_committed(
+    broker: CommonBroker,
+    caller: NodeId,
+    msg: AgreementCommitted,
+) -> Result<(), RemoteCommitAgreementError> {
+    let dao = broker.db.as_dao::<AgreementDao>();
+    let agreement = {
+        let _hold = broker.agreement_lock.lock(&msg.agreement_id).await;
+
+        // Note: we still validate caller here, because we can't be sure, that we were caller
```
Comment (jiivan) [inline core/market/src/negotiation/provider.rs:302]:
```suggestion
        // Note: we still validate caller here, because we can't be sure, that we were called
```

File: core/market/src/negotiation/requestor.rs [hunk 3]
```diff
@@ -451,41 +443,92 @@ async fn agreement_approved(
...
+        &agreement.id,
+        &agreement.provider_id
+    );
+    Ok(())
+}
+
+async fn commit_agreement(broker: CommonBroker, agreement_id: AgreementId) {
+    // Note: in this scenario, we update database after Provider already
+    // got `AgreementCommitted` and updated Agreement state to `Approved`, so we will
+    // wake up `wait_for_agreement` after Provider.
```
Comment (jiivan) [inline core/market/src/negotiation/requestor.rs:473]: :+1:

**Review by jiivan — COMMENTED** [review]
LGTM. Lots'a good docstrings! :+1: Lets see the final code!

File: core/market/src/utils/agreement_lock.rs [hunk 4]
```diff
@@ -16,7 +16,7 @@ impl AgreementLock {
         }
     }
 
-    pub async fn get_lock(&self, agreement_id: &AgreementId) -> Arc<Mutex<()>> {
+    pub async fn lock(&self, agreement_id: &AgreementId) -> OwnedMutexGuard<()> {
```
Comment (tworec) [inline core/market/src/utils/agreement_lock.rs:19]: ❤️

File: core/market/src/negotiation/provider.rs [hunk 5]
```diff
@@ -51,6 +52,7 @@ impl ProviderBroker {
         let broker3 = broker.clone();
         let broker_proposal_reject = broker.clone();
         let broker_terminated = broker.clone();
+        let commit_broker = broker.clone();
```
Comment (tworec) [inline core/market/src/negotiation/provider.rs:55]: I have in some old branch, a builder for Brokers, that would allow to get rid of this, but I'm to shy (read: it is to close to Mainnet release) to reveal it now ;)

File: core/market/src/negotiation/provider.rs [hunk 6]
```diff
@@ -228,37 +230,110 @@ impl ProviderBroker {
...
+    broker: CommonBroker,
+    caller: NodeId,
+    msg: AgreementCommitted,
+) -> Result<(), RemoteCommitAgreementError> {
+    let dao = broker.db.as_dao::<AgreementDao>();
+    let agreement = {
+        let _hold = broker.agreement_lock.lock(&msg.agreement_id).await;
+
+        // Note: we still validate caller here, because we can't be sure, that we were caller
+        // by the same Requestor.
```
Comment (tworec) [inline core/market/src/negotiation/provider.rs:303]: 👍

File: core/market/src/negotiation/provider.rs [hunk 7]
```diff
@@ -228,37 +230,110 @@ impl ProviderBroker {
...
+        };
+
+        // Note: We can find out here, that our Agreement is already in `Cancelled` state, because
+        // Requestor is allowed to call `cancel_agreement` at any time, before we commit Agreement.
+        // In this case we should return here, but we still must call `notify_agreement` to wake other threads.
+        validate_transition(&agreement, AgreementState::Approving)?;
+
+        // TODO: Validate committed signature from message.
+
+        // TODO: `approve` shouldn't set AppSessionId anymore.
```
Comment (tworec) [inline core/market/src/negotiation/provider.rs:320]: Indeed. Change state to `Approving` should set `AppSessId`, as you've marked in TODO above already.

File: core/market/src/negotiation/provider.rs [hunk 8]
```diff
@@ -228,37 +230,110 @@ impl ProviderBroker {
...
+            .await
+            .map_err(|e| AgreementError::Get(msg.agreement_id.to_string(), e))?
+        {
+            None => Err(AgreementError::NotFound(msg.agreement_id.to_string()))?,
+            Some(agreement) => agreement,
+        };
+
+        // Note: We can find out here, that our Agreement is already in `Cancelled` state, because
+        // Requestor is allowed to call `cancel_agreement` at any time, before we commit Agreement.
+        // In this case we should return here, but we still must call `notify_agreement` to wake other threads.
```
Comment (tworec) [inline core/market/src/negotiation/provider.rs:315]: I think they have been already wakened up as a side effect of `cancel_agreement` or other `commit_agreement` which is also possible in between. But `notifying` more is better than less.

File: core/market/src/negotiation/requestor.rs [hunk 9]
```diff
@@ -67,7 +67,10 @@ impl RequestorBroker {
             move |caller: String, msg: AgreementApproved| {
                 on_agreement_approved(broker2.clone(), caller, msg)
             },
-            move |_caller: String, _msg: AgreementRejected| async move { unimplemented!() },
+            move |_caller: String, _msg: AgreementRejected| async move {
+                counter!("market.agreements.requestor.rejected", 1);
```
Comment (tworec) [inline core/market/src/negotiation/requestor.rs:71]: 👍

File: core/market/src/negotiation/requestor.rs [hunk 10]
```diff
@@ -451,41 +443,92 @@ async fn agreement_approved(
...
+        // TODO: Sign Agreement and update `approved_signature`.
+        // TODO: Update `approved_ts` Agreement field.
+        // TODO: Update state to `AgreementState::Approving`.
+
+        agreement
+    };
+
+    /// TODO: Commit Agreement. We must spawn committing later, because we need to
+    ///  return from this function to provider.
+    tokio::task::spawn_local(commit_agreement(broker, agreement.id));
```
Comment (tworec) [inline core/market/src/negotiation/requestor.rs:461]: 👍

File: core/market/src/negotiation/requestor.rs [hunk 11]
```diff
@@ -311,15 +314,12 @@ impl RequestorBroker {
 
             match agreement.state {
                 AgreementState::Approved => {
-                    counter!("market.agreements.requestor.approved", 1);
```
Comment (tworec) [inline core/market/src/negotiation/requestor.rs:314]: 👍

**Review by tworec — COMMENTED** [review]
Looks very promising. Keep going

File: core/market/src/protocol/negotiation/messages.rs [hunk 12]
```diff
@@ -176,6 +188,20 @@ impl RpcMessage for AgreementTerminated {
...
+#[derive(Debug, Clone, Serialize, Deserialize)]
+#[serde(rename_all = "camelCase")]
+pub struct AgreementCommitted {
+    pub agreement_id: AgreementId,
+    /// This will be placed in `committed_signature` Agreement field.
+    pub signature: String,
+}
+
+impl RpcMessage for AgreementCommitted {
+    const ID: &'static str = "CommitAgreement";
```
[the remark this answers is not in the document]
Comment (nieznanysprawiciel) [reply core/market/src/protocol/negotiation/messages.rs:200]: Good you noticed

File: core/market/src/protocol/negotiation/messages.rs [hunk 13]
```diff
@@ -130,7 +131,12 @@ impl RpcMessage for AgreementReceived {
 #[serde(rename_all = "camelCase")]
 pub struct AgreementApproved {
     pub agreement_id: AgreementId,
-    // TODO: We should send here signature.
+    /// This will be placed in `approved_signature` Agreement field.
+    pub signature: String,
+    /// This timestamp will differ from timestamp, when Agreement will be updated in
+    /// database to `Approved` state and `AgreementApprovedEvent` timestamp either.
+    /// But we can't set it to any value, because we should include this field in signature.
```
[the remark this answers is not in the document]
Comment (nieznanysprawiciel) [reply core/market/src/protocol/negotiation/messages.rs:138]: I don't know how to clarify this, but I have feeling, that you missed the main point, that requires some consideration:
We have `approved_ts`  in Agreement, but we can't set this value at the moment, when Agreement changed state to `Approved`. And we can't do this, because this timestamp should be signed by Provider and he sends his signature, when Proposal changes state to `Approving`.

File: core/market/src/utils/agreement_lock.rs [hunk 14]
```diff
@@ -36,7 +36,8 @@ impl AgreementLock {
                     .clone()
             }
         }
-        .clone()
+        .lock_owned()
```
[the remark this answers is not in the document]
Comment (nieznanysprawiciel) [reply core/market/src/utils/agreement_lock.rs:39]: No it wasn't. This is simplification that allows us to return `OwnedLockGuard` from this function and simplify locks in outside code

[the remark this answers is not in the document]
Comment (tworec) [reply core/market/src/utils/agreement_lock.rs:39]: So what was the #1014 fix about?

File: core/market/src/db/dao/agreement.rs [hunk 15]
```diff
@@ -296,6 +346,40 @@ fn update_state(
...
+    ColumnSelector:
+        diesel::expression_methods::ExpressionMethods + Column<Table = market_agreement>,
+{
+    let signature = Some(signature);
+    let num_updated = diesel::update(market_agreement.find(&agreement.id))
+        .set(column.eq(&signature))
+        .execute(conn)
+        .map_err(|e| AgreementDaoError::DbError(e.into()))?;
+
+    agreement.approved_signature = signature;
```
Comment (tworec) [inline core/market/src/db/dao/agreement.rs:365]: ⚠️ bug. You do not know which column to update on the struct, so you can not do it inside this fn.
Unless you select the db again here. which is not most optimal, but acceptable.

File: core/market/src/negotiation/provider.rs [hunk 16]
```diff
@@ -212,53 +219,173 @@ impl ProviderBroker {
...
+                    &session,
+                    &agreement.id
+                );
+            }
             agreement
         };
 
-        self.common.notify_agreement(&agreement).await;
+        // Listen to Agreements notification before we start sending message, because otherwise
+        // we can lose events.
```
Comment (tworec) [inline core/market/src/negotiation/provider.rs:252]: I do not see how we can lose events here

File: core/market/src/protocol/negotiation/messages.rs (hunk 13 above)
[the remark this answers is not in the document]
Comment (tworec) [reply core/market/src/protocol/negotiation/messages.rs:140]: You're right: the `approved_ts` should be signed by both sides, so it needs to be specified when the provider sends this message, with its only signature for the Agreement. Then Requestor will create its second signature which will also cover the `approved_ts`.

My point is that the last sentence of your comment is not clear, or even false. We can and must set the `approved_ts` here. And you are doing this in the code below:

https://github.com/golemfactory/yagna/pull/1015/files#diff-b5dd89d987b0df3b7532481d3ef3990172d23e8a6b746e625ff346ee6ffa9ac0R125-R127

File: core/market/src/negotiation/provider.rs (hunk 16 above)
Comment (nieznanysprawiciel) [reply core/market/src/negotiation/provider.rs:255]: If listener doesn't exist, channel doesn't collect notifications. We must create channel first and than send message, which can result in event

File: core/market/src/utils/agreement_lock.rs (hunk 14 above)
[the remark this answers is not in the document]
Comment (nieznanysprawiciel) [reply core/market/src/utils/agreement_lock.rs:39]: It's about this timeout. But `lock_owned` didn't fix anything. Other part of this PR did

File: core/market/src/protocol/negotiation/error.rs [hunk 17]
```diff
@@ -141,6 +141,22 @@ pub enum RemoteAgreementError {
     InternalError(AgreementId),
 }
 
+#[derive(Error, Debug, Serialize, Deserialize)]
+pub enum CommitAgreementError {
+    #[error("Remote Commit Agreement [{1}] error: {0}")]
+    Remote(RemoteCommitAgreementError, AgreementId),
```
[the remark this answers is not in the document]
Comment (nieznanysprawiciel) [reply core/market/src/protocol/negotiation/error.rs:158]: I kept `AgreementId` here and removed it from `RemoteCommitAgreementError`

File: core/market/src/negotiation/provider.rs [hunk 18]
```diff
@@ -210,50 +219,211 @@ impl ProviderBroker {
...
                 .map_err(|e| AgreementError::Get(agreement_id.to_string(), e))?
-            {
-                None => Err(AgreementError::NotFound(agreement_id.to_string()))?,
-                Some(agreement) => agreement,
-            };
+                .ok_or(AgreementError::NotFound(agreement_id.to_string()))?;
 
-            validate_transition(&agreement, AgreementState::Approved)?;
+            if agreement.state == AgreementState::Cancelled {
+                return Ok(ApprovalResult::Cancelled);
```
Comment (tworec) [inline core/market/src/negotiation/provider.rs:234]: 👍

File: core/market/src/negotiation/provider.rs [hunk 19]
```diff
@@ -210,50 +219,211 @@ impl ProviderBroker {
...
-            log::info!(
-                "AppSession id [{}] set for Agreement [{}].",
-                &session,
-                &agreement_id
-            );
+
+        // Here we must wait until `AgreementCommitted` message, since `approve_agreement`
+        // is supposed to return after approval.
+        let timeout =
+            std::time::Duration::from_secs_f64(timeout as f64) - (Instant::now() - start_now);
```
Comment (tworec) [inline core/market/src/negotiation/provider.rs:305]: check negative timeout

File: core/market/src/negotiation/requestor.rs [hunk 20]
```diff
@@ -441,43 +444,129 @@ async fn agreement_approved(
...
+    .await
+    {
+        Ok(agreement) => agreement,
+        // Return to `Pending` state here unless we are in `Cancelled` state.
+        Err(AgreementError::ProtocolCommit(CommitAgreementError::Remote(
+            RemoteCommitAgreementError::Cancelled,
+            _,
+        ))) => {
+            return log::info!(
+                "Didn't commit Agreement [{}] since it was cancelled.",
```
Comment (tworec) [inline core/market/src/negotiation/requestor.rs:538]:
```suggestion
                "Can't commit Agreement [{}] since it was canceled already.",
```

File: core/market/src/negotiation/requestor.rs [hunk 21]
```diff
@@ -441,43 +444,129 @@ async fn agreement_approved(
...
+                    agreement_id
+                ))
+                .ok();
+            return;
+        }
+    };
+
+    broker.notify_agreement(&agreement).await;
+
+    counter!("market.agreements.requestor.approved", 1);
```
Comment (tworec) [inline core/market/src/negotiation/requestor.rs:562]: add `approving` and `commit` counters

File: core/market/src/db/model/agreement.rs [hunk 22]
```diff
@@ -199,8 +204,14 @@ pub fn check_transition(from: AgreementState, to: AgreementState) -> Result<(),
...
         },
         AgreementState::Pending => match to {
+            AgreementState::Approving => return Ok(()),
             AgreementState::Cancelled => return Ok(()),
             AgreementState::Rejected => return Ok(()),
+            AgreementState::Expired => return Ok(()),
+            _ => (),
+        },
+        AgreementState::Approving => match to {
+            AgreementState::Cancelled => return Ok(()),
```
Comment (tworec) [inline core/market/src/db/model/agreement.rs:214]:
```suggestion
            // Reverse transition from `Approving` to `Pending` is forbidden on purpose. It is handled solely in `revert_approving()`
            AgreementState::Cancelled => return Ok(()),
```

File: core/market/src/negotiation/requestor.rs [hunk 23]
```diff
@@ -329,7 +331,7 @@ impl RequestorBroker {
                 AgreementState::Terminated => {
                     return Err(WaitForApprovalError::Terminated(id.clone()))
                 }
-                AgreementState::Pending => (), // Still waiting for approval.
+                AgreementState::Pending | AgreementState::Approving => (), // Still waiting for approval.
             };
 
             if let Err(error) = notifier.wait_for_event_with_timeout(timeout).await {
```
Comment (tworec) [inline core/market/src/negotiation/requestor.rs:337]: nitpick: use fixed point in time to stop waiting rather than relative timeout

**Review by tworec — APPROVED** [review]
lgtm
