### PR TITLE
Fix for ExeUnit `cache` and `cache/tmp` mounted on different devices

### LINKED ISSUE #289: Market Discovery - unsubscribe
#### Pre-conditions
- Yagna daemon is connected to network
- Agent is connected to yagna daemon

#### Scenario
1. Provider subscribes Offer
    - [x] _Offer_ is added to database
    - [x] Matching with existing _Demands_ is spawned (No results yet, since there are no _Demands_)
    - [x] _Offer_ is available at `/offers/{subscription_id}` endpoint
    - [x] Broadcasting _Offer_ to the network
1. Remote Nodes
    - [x] _Offer_ is available on all other nodes in network
    - [x] Matching with existing _Demands_ on other nodes is spawned
1. Provider unsubscribes offer (delete `/offers/{subscription_id}`)
    - [x] _Offer_ is marked as unsubscribed on local node
    - [x] Unsubscribe event is broadcasted to remote nodes
    - [x] _Offer_ is not available at `/offers` endpoint
1. Remote Nodes
    - [x] Unsubscribe message is received
    - [x] _Offer_ is removed from database
    - [x] _Offer_ is marked as unsubscribed on remote nodes
    - [x] _Offer_ is not available at `/offers` endpoint

### PR DESCRIPTION
**Pull request by mfranciszkiewicz**
Resolves https://github.com/golemfactory/golem-internal/issues/289

### CODE REVIEW

File: exe-unit/src/service/transfer.rs [hunk 1]
```diff
@@ -1,19 +1,22 @@
...
+use std::convert::TryFrom;
+use std::io;
+use std::path::{Path, PathBuf};
+use std::rc::Rc;
+use std::time::{SystemTime, UNIX_EPOCH};
+
+use actix::prelude::*;
+use futures::future::Abortable;
+use url::Url;
+
```
Comment (tworec) [inline exe-unit/src/service/transfer.rs:11]: 💘

**Review by tworec — APPROVED** [review]

**Comment by tworec** [comment]
cherrypicked it also to `master` (via 2268e9f3) and to `release/v0.6` (via c37dbd1a)
