### PR TITLE
Disallow creating agreement on rejected proposal

### LINKED ISSUE #1518: Creating agreement on rejected proposal
Why: Requestor's request to create an agreement on rejected proposal should fail immediately. 
What: Requestor is able to create an agreement on rejected counter proposal.
```
[2021-07-16T11:05:08.218+0200 INFO  ya_market::negotiation::common] Requestor [0x6c1a5409a97c657c4c82f8a5caa9bbe
a5c955082] rejected Proposal [R-f537d5f43b88fd753c8b1d2fa96bb0fc853ff148b26fcf3ec416c159cf11ffc1] 'Rejected'.   
[2021-07-16T11:05:13.314+0200 INFO  ya_market::negotiation::requestor] Requestor 'golem-cli' [0x6c1a5409a97c657c
4c82f8a5caa9bbea5c955082] created Agreement [R-329aed1c57279b36fdf975d2980cc1249f8cfa46dd5e1a391481a798a2940d48]
 from Proposal [R-f537d5f43b88fd753c8b1d2fa96bb0fc853ff148b26fcf3ec416c159cf11ffc1].                            
[2021-07-16T11:05:13.408+0200 INFO  ya_market::negotiation::requestor] Requestor 'golem-cli' [0x6c1a5409a97c657c
4c82f8a5caa9bbea5c955082] confirmed Agreement [R-329aed1c57279b36fdf975d2980cc1249f8cfa46dd5e1a391481a798a2940d4
8] and sent to Provider.                                                                                        
[2021-07-16T11:05:28.418+0200 ERROR ya_market::rest_api::requestor::wait_for_approval] Error occurred: Timeout w
hile waiting for Agreement [R-329aed1c57279b36fdf975d2980cc1249f8cfa46dd5e1a391481a798a2940d48] approval.
```

### PR DESCRIPTION
**Pull request by tworec**
Fixes #1518

### CODE REVIEW

File: core/market/src/negotiation/requestor.rs [hunk 1]
```diff
@@ -249,6 +250,23 @@ impl RequestorBroker {
...
+                return Err(AgreementError::NoNegotiations(proposal_id.clone()))
+            }
+            ProposalState::Rejected => {
+                return Err(AgreementError::ProposalRejected(proposal_id.clone()))
+            }
+            ProposalState::Accepted => {
+                return Err(AgreementError::ProposalAlreadyAccepted(proposal_id.clone()))
+            }
+            ProposalState::Expired => {
+                // TODO: expiration of proposals is never checked
```
Comment (tworec) [inline core/market/src/negotiation/requestor.rs:267]: This should be fixed in separate PR.

File: core/market/src/negotiation/error.rs [hunk 2]
```diff
@@ -48,18 +48,20 @@ pub enum AgreementError {
...
     #[error("Agreement [{0}] expired.")]
     Expired(AgreementId),
-    #[error("Can't create Agreement for Proposal {0}. Proposal {1} not found.")]
+    #[error("Can't create Agreement for Proposal [{0}]. Proposal [{1}] not found.")]
     ProposalNotFound(ProposalId, ProposalId),
-    #[error("Can't create second Agreement [{0}] for Proposal [{1}].")]
-    AlreadyExists(AgreementId, ProposalId),
-    #[error("Can't create Agreement for Proposal {0}. Failed to get Proposal {1}. Error: {2}")]
+    #[error("Can't create second Agreement for Proposal [{0}].")]
+    ProposalAlreadyAccepted(ProposalId),
```
Comment (tworec) [inline core/market/src/negotiation/error.rs:54]: Simplification of the error message.

**Review by nieznanysprawiciel — APPROVED** [review]

File: core/market/src/negotiation/error.rs [hunk 3]
```diff
@@ -48,18 +48,20 @@ pub enum AgreementError {
...
+    #[error("Can't create Agreement for Proposal [{0}]. Failed to get Proposal [{1}]. Error: {2}")]
     GetProposal(ProposalId, ProposalId, String),
     #[error("Can't create Agreement for already countered Proposal [{0}].")]
     ProposalCountered(ProposalId),
-    #[error("Can't create Agreement for Proposal {0}. No negotiation with Provider took place. (You should counter Proposal at least one time)")]
+    #[error("Can't create Agreement for Proposal [{0}]. No negotiation with Provider took place. (You should counter Proposal at least one time)")]
     NoNegotiations(ProposalId),
-    #[error("Can't create Agreement for out own Proposal {0}. You can promote only provider's Proposals to Agreement.")]
+    #[error("Can't create Agreement for an own Proposal [{0}]. You can promote only provider's Proposals to Agreement.")]
```
Comment (jiivan) [inline core/market/src/negotiation/error.rs:61]: Should be "our own".
